name: shmart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  ai_barcode_scanner: ^3.4.3
  animate_do: ^3.3.4
  cloud_firestore: ^4.15.8
  dio: ^5.4.1
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  share: ^2.0.4
  shared_preferences: ^2.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/bg-white-logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Dashiki 
      fonts:
        - asset: assets/Font.ttf
    - family: Dashiki-Bold
      fonts:
        - asset: assets/FontBold.ttf
